"""Instrument snapshots persisted solely through the existing governed registry."""

from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime
from threading import Lock

from quant_hunter.config import JsonRecord
from quant_hunter.identity import (
    RegistryKind,
    RegistryStore,
    Revision,
    new_typed_id,
    validate_typed_id,
)
from quant_hunter.markets import InstrumentHistory, InstrumentRevision, MarketError

MANAGED_FIELDS = {
    "schema_version",
    "instrument_id",
    "revision",
    "previous_revision_digest",
}


class InstrumentRegistry:
    """Reference metadata shared within this local installation, owner writes only.

    The caller controls authentication. Recorded time is generated by the service,
    not accepted from an upload. It establishes local knowledge, never asserts a
    provider's historical publication date. The canonical registry owns CAS/history.
    """

    def __init__(
        self,
        store: RegistryStore,
        *,
        clock: Callable[[], datetime] = lambda: datetime.now(UTC),
    ) -> None:
        self.store, self.clock = store, clock
        self._admission = Lock()

    def _history(
        self, instrument_id: str
    ) -> tuple[tuple[Revision, ...], InstrumentHistory]:
        validate_typed_id(instrument_id, RegistryKind.INSTRUMENT)
        revisions = self.store.verify_object(instrument_id)
        snapshots: list[InstrumentRevision] = []
        for row in revisions:
            payload = {
                key: value
                for key, value in row.record.items()
                if key not in MANAGED_FIELDS
            }
            snapshot = InstrumentRevision.from_record(payload)
            if snapshot.instrument.instrument_id != instrument_id:
                raise MarketError(
                    "Instrument envelope and metadata identities disagree"
                )
            snapshots.append(snapshot)
        return revisions, InstrumentHistory(tuple(snapshots))

    def _snapshot(self, instrument_id: str, payload: JsonRecord) -> InstrumentRevision:
        if set(payload) != {
            "instrument",
            "reason",
            "evidence_mode",
            "source_reference",
        }:
            raise MarketError(
                "Metadata requires instrument, reason, evidence mode and source reference"
            )
        instrument = payload["instrument"]
        if not isinstance(instrument, dict) or "instrument_id" in instrument:
            raise MarketError(
                "The server allocates and binds stable instrument identity"
            )
        value: JsonRecord = {
            **payload,
            "instrument": {**instrument, "instrument_id": instrument_id},
            "recorded_at": self.clock().isoformat().replace("+00:00", "Z"),
        }
        return InstrumentRevision.from_record(value)

    def create(self, payload: JsonRecord) -> JsonRecord:
        with self._admission:
            return self._create(payload)

    def _create(self, payload: JsonRecord) -> JsonRecord:
        root = self.store.root / RegistryKind.INSTRUMENT.directory
        if root.exists() and sum(1 for path in root.iterdir() if path.is_dir()) >= 1000:
            raise MarketError("Instrument profile is bounded at 1000 identities")
        identity = new_typed_id(RegistryKind.INSTRUMENT)
        snapshot = self._snapshot(identity, payload)
        self.store.create_initial(
            RegistryKind.INSTRUMENT,
            identity,
            {"schema_version": "1.0.0", **snapshot.to_record()},
        )
        return self.get(identity)

    def update(
        self, instrument_id: str, expected_digest: str, payload: JsonRecord
    ) -> JsonRecord:
        _, history = self._history(instrument_id)
        snapshot = self._snapshot(instrument_id, payload)
        InstrumentHistory((*history.revisions, snapshot))
        # Expected canonical digest is independently checked under RegistryStore's
        # lock. A stale caller cannot overwrite the intervening metadata revision.
        self.store.append(
            instrument_id,
            expected_digest,
            {"schema_version": "1.0.0", **snapshot.to_record()},
        )
        return self.get(instrument_id)

    def get(self, instrument_id: str) -> JsonRecord:
        revisions, history = self._history(instrument_id)
        return {
            "record": revisions[-1].record,
            "digest": revisions[-1].digest,
            "revision_count": len(history.revisions),
            "historical_availability": "LOCAL_RECORDED_TIME_ONLY",
            "empirically_validated": False,
        }

    def as_of(
        self, instrument_id: str, knowledge_time: datetime, effective_time: datetime
    ) -> JsonRecord:
        revisions, history = self._history(instrument_id)
        instrument = history.as_of(knowledge_time, effective_time)
        index = max(
            index
            for index, snapshot in enumerate(history.revisions)
            if snapshot.recorded_at <= knowledge_time
        )
        snapshot = history.revisions[index]
        return {
            "record": snapshot.to_record(),
            "registry_digest": revisions[index].digest,
            "symbol": instrument.symbol_at(effective_time),
            "historical_availability": "LOCAL_RECORDED_TIME_ONLY",
        }

    def list(self, *, limit: int = 25, offset: int = 0) -> list[JsonRecord]:
        if (
            type(limit) is not int
            or not 1 <= limit <= 50
            or type(offset) is not int
            or not 0 <= offset <= 1000
        ):
            raise MarketError("Invalid instrument page")
        root = self.store.root / RegistryKind.INSTRUMENT.directory
        if not root.exists():
            return []
        paths = sorted(root.iterdir(), key=lambda path: path.name)
        return [
            self.get(path.name)
            for path in paths[offset : offset + limit]
            if path.is_dir()
        ]
