"""Bounded CRP mathematics. Synthetic tests establish no empirical trading claim."""

from .common import MethodError, TimedRow
from .ensemble import (
    EnsembleFit,
    MetaFit,
    OOFPrediction,
    ensemble_prediction,
    fit_covariance_ensemble,
    fit_temporal_meta,
    meta_prediction,
)
from .events import (
    BookUpdate,
    MacroRelease,
    OrderFlow,
    SurpriseScale,
    fit_surprise_scale,
    macro_surprise,
    order_flow_imbalance,
)
from .fitted import (
    CointegrationFit,
    PCAFit,
    ecm_forecast,
    fit_cointegration,
    fit_pca,
    pca_residual,
)
from .signals import (
    CarrySignal,
    MomentumSignal,
    ValueRelease,
    forward_carry,
    fx_cross_section_momentum,
    time_series_momentum,
    value_momentum,
)
from .volatility import (
    GARCHFit,
    ewma_variances,
    fit_garch,
    garch_forecast,
    garch_variances,
    inverse_volatility_weights,
    portfolio_net_return,
    rolling_inverse_volatility,
    variance_scores,
    volatility_managed_exposure,
)

__all__ = [
    "BookUpdate",
    "CarrySignal",
    "CointegrationFit",
    "EnsembleFit",
    "GARCHFit",
    "MacroRelease",
    "MetaFit",
    "MethodError",
    "MomentumSignal",
    "OOFPrediction",
    "OrderFlow",
    "PCAFit",
    "SurpriseScale",
    "TimedRow",
    "ValueRelease",
    "ecm_forecast",
    "ensemble_prediction",
    "ewma_variances",
    "fit_cointegration",
    "fit_covariance_ensemble",
    "fit_garch",
    "fit_pca",
    "fit_surprise_scale",
    "fit_temporal_meta",
    "forward_carry",
    "fx_cross_section_momentum",
    "garch_forecast",
    "garch_variances",
    "inverse_volatility_weights",
    "macro_surprise",
    "meta_prediction",
    "order_flow_imbalance",
    "pca_residual",
    "portfolio_net_return",
    "rolling_inverse_volatility",
    "time_series_momentum",
    "value_momentum",
    "variance_scores",
    "volatility_managed_exposure",
]
